from supabase import create_client, Client
from config import settings
import logging
import asyncio
from functools import partial

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class SupabaseClient:
    def __init__(self):
        self.client: Client = None
        self._initialized = False
    
    def connect(self):
        """Initialize connection to Supabase (lazy initialization)"""
        if self._initialized:
            return
            
        try:
            if not settings.SUPABASE_URL or not settings.SUPABASE_KEY:
                logger.warning("SUPABASE_URL and SUPABASE_KEY are not set. Supabase client will not be available.")
                self._initialized = True
                return
            
            # Check if URL is valid (not empty string)
            if settings.SUPABASE_URL.strip() == "" or settings.SUPABASE_KEY.strip() == "":
                logger.warning("SUPABASE_URL or SUPABASE_KEY is empty. Supabase client will not be available.")
                self._initialized = True
                return
            
            self.client = create_client(settings.SUPABASE_URL, settings.SUPABASE_KEY)
            self._initialized = True
            logger.info("Successfully connected to Supabase")
        except Exception as e:
            logger.error(f"Failed to connect to Supabase: {e}")
            self._initialized = True
            # Don't raise - allow the app to start even if Supabase is not configured
    
    def get_client(self) -> Client:
        """Get the Supabase client instance"""
        if not self._initialized:
            self.connect()
        return self.client
    
    async def insert_data(self, table_name: str, json_data: dict):
        """Insert data into a Supabase table with simplified schema (truly async)"""
        try:
            # Ensure client is initialized
            if not self._initialized:
                self.connect()
            
            if not self.client:
                logger.warning(f"Supabase client not available. Skipping insert to {table_name}")
                return None
            
            # Prepare data for the simplified schema (id, created_at, json_data)
            data = {
                "json_data": json_data
                # id and created_at will be auto-generated by the database
            }
            
            # Run blocking Supabase operation in thread pool to avoid blocking event loop
            logger.info(f"🔄 Attempting to insert data into {table_name}...")
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(
                None, 
                partial(self.client.table(table_name).insert(data).execute)
            )
            logger.info(f"✅ Data inserted successfully into {table_name}, record ID: {result.data[0].get('id') if result.data else 'unknown'}")
            return result
        except Exception as e:
            logger.error(f"❌ Error inserting data into {table_name}: {e}")
            logger.exception(e)  # Print full traceback
            raise
    
    async def get_data(self, table_name: str, filters: dict = None):
        """Retrieve data from a Supabase table (truly async)"""
        try:
            # Ensure client is initialized
            if not self._initialized:
                self.connect()
            
            if not self.client:
                logger.warning(f"Supabase client not available. Skipping get from {table_name}")
                return None
            
            query = self.client.table(table_name).select("*")
            
            if filters:
                for key, value in filters.items():
                    query = query.eq(key, value)
            
            # Run blocking Supabase operation in thread pool
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, query.execute)
            logger.info(f"Data retrieved successfully from {table_name}")
            return result
        except Exception as e:
            logger.error(f"Error retrieving data from {table_name}: {e}")
            raise
    
    async def update_data(self, table_name: str, data: dict, filters: dict):
        """Update data in a Supabase table (truly async)"""
        try:
            # Ensure client is initialized
            if not self._initialized:
                self.connect()
            
            if not self.client:
                logger.warning(f"Supabase client not available. Skipping update to {table_name}")
                return None
            
            query = self.client.table(table_name).update(data)
            
            for key, value in filters.items():
                query = query.eq(key, value)
            
            # Run blocking Supabase operation in thread pool
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, query.execute)
            logger.info(f"Data updated successfully in {table_name}")
            return result
        except Exception as e:
            logger.error(f"Error updating data in {table_name}: {e}")
            raise
    
    async def get_latest_by_json_field(self, table_name: str, json_field: str, json_value: str, limit: int = 1):
        """
        Get the latest record(s) from a table filtered by a field inside json_data column
        Optimized to filter in the database instead of downloading all records
        
        Args:
            table_name: Name of the table
            json_field: Field name inside json_data to filter by (e.g., 'bus_id')
            json_value: Value to match
            limit: Number of records to return (default 1 for latest)
        """
        try:
            # Ensure client is initialized
            if not self._initialized:
                self.connect()
            
            if not self.client:
                logger.warning(f"Supabase client not available. Skipping get from {table_name}")
                return None
            
            # Use PostgreSQL JSON operator to filter by field inside json_data
            # The ->> operator extracts JSON field as text
            query = (
                self.client.table(table_name)
                .select("*")
                .eq(f"json_data->{json_field}", json_value)  # Filter by JSON field
                .order("created_at", desc=True)  # Get most recent first
                .limit(limit)
            )
            
            # Run blocking Supabase operation in thread pool
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, query.execute)
            logger.info(f"Query executed on {table_name} filtered by {json_field}={json_value}")
            return result
        except Exception as e:
            logger.error(f"Error querying {table_name} with json filter: {e}")
            raise

# Global instance
supabase_client = SupabaseClient()
